# Generated by Django 3.1.2 on 2020-10-26 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0005_auto_20201026_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lattitude', models.FloatField()),
                ('logitude', models.FloatField()),
                ('country_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insta.location'),
        ),
    ]
